# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=018c365850
# 
# 

# ********RoostGPT********
Feature: Pet Store API Tests

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'dummyToken')
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Get pet by ID
  Given path '/v2/pet/{petId}'
  And params { petId: '#(petId)' }
  When method get
  Then status 200
  And match response ==
  """
  {
    "id": "#number",
    "category": {
      "id": "#number",
      "name": "#string"
    },
    "name": "#string",
    "photoUrls": "#[]string",
    "tags": [
      {
        "id": "#number",
        "name": "#string"
      }
    ],
    "status": "#string"
  }
  """
  Examples:
  | petId |
  | 1     |
  | 2     |
  | 3     |

Scenario: Get pet by ID - Invalid ID supplied
  Given path '/v2/pet/{petId}'
  And params { petId: '#(petId)' }
  When method get
  Then status 400
  Examples:
  | petId  |
  | 'abc'  |
  | '-1'   |
  | '0'    |

Scenario: Get pet by ID - Pet not found
  Given path '/v2/pet/{petId}'
  And params { petId: '#(petId)' }
  When method get
  Then status 404
  Examples:
  | petId |
  | 99999 |
  | 88888 |
  | 77777 |
