# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=467fc95f1c
# 
# 

# ********RoostGPT********
Feature: Test /v2/pet/findByStatus API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'sample_auth_token')
  * configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Test GET /v2/pet/findByStatus with valid status
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status 200
  And match each response contains { name:'#string', photoUrls:'#array' }
  And match each response contains { 'id':'#number', 'category.id':'#number', 'category.name':'#string', 'name':'#string', 'photoUrls':'#array', 'tags':'#array', 'status':'#string' }

Examples:
  | status   |
  | 'available' |
  | 'pending' |
  | 'sold'    |

Scenario: Test GET /v2/pet/findByStatus with invalid status
  Given path '/v2/pet/findByStatus'
  And param status = 'invalid_status'
  When method get
  Then status 400
