# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=018c365850
# 
# 

# ********RoostGPT********
Feature: Pet Store API Tests

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.get('authToken', karate.properties['auth.token'])
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Find pet by ID
  Given path '/v2/pet/', 1
  When method get
  Then status 200
  And match response == { id: '#number', category: '#object', name: 'doggie', photoUrls: '#[]', tags: '#[]', status: '#string' }
  And match response.id == 1
  And match response.name == 'doggie'

Scenario Outline: Find pet by ID with different petIds
  Given path '/v2/pet/', <petId>
  When method get
  Then status 200
  And match response.id == <petId>

  Examples:
    | petId |
    | 2     |
    | 3     |
    | 4     |

Scenario: Find pet by ID - pet not found
  Given path '/v2/pet/', 999999999
  When method get
  Then status 404

Scenario: Find pet by ID - invalid ID supplied
  Given path '/v2/pet/', 'invalid'
  When method get
  Then status 400
