# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_post for http method type POST 
# RoostTestHash=c0bc5294a0
# 
# 

# ********RoostGPT********
Feature: Pet Store API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'defaultToken')
    * configure headers = { Authorization: '#(authToken)' }

  Scenario Outline: Test update pet with form data
    Given path 'v2', 'pet', '<petId>'
    And param name = '<name>'
    And param status = '<status>'
    When method post
    Then status 200
    And match responseHeaders contains { 'Content-Type': 'application/json' }
    And match response == { id: '#(petId)', name: '<name>', status: '<status>' }

    Examples:
      | petId | name       | status    |
      | 1     | 'Fluffy'   | 'sold'    |
      | 2     | 'Spike'    | 'pending' |
      | 3     | 'Goldie'   | 'available' |
