# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/order_post for http method type POST 
# RoostTestHash=8153b7f54d
# 
# 

# ********RoostGPT********
Feature: Place an order for a pet

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['auth.token'] || karate.get('authToken')
    * configure headers = {Authorization: '#(authToken)'}

Scenario Outline: Verify placing order for a pet
    Given path '/v2/store/order'
    And request
    """
    {
        "id": "<id>",
        "petId": "<petId>",
        "quantity": "<quantity>",
        "shipDate": "<shipDate>",
        "status": "<status>",
        "complete": "<complete>"
    }
    """
    When method post
    Then status <statusCode>
    And match response ==
    """
    {
        "id": "#(<id>)",
        "petId": "#(<petId>)",
        "quantity": "#(<quantity>)",
        "shipDate": "<shipDate>",
        "status": "<status>",
        "complete": "<complete>"
    }
    """
    Examples:
    | id | petId | quantity | shipDate         | status    | complete | statusCode |
    | 1  | 101   | 2        | '2022-01-01T18:30:00.000Z' | 'placed' | true      | 200        |
    | 2  | 102   | 3        | '2022-01-02T18:30:00.000Z' | 'delivered' | false     | 200        |
    | 3  | 103   | 4        | '2022-01-03T18:30:00.000Z' | 'placed' | true      | 200        |
