# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/order/{orderId}_delete for http method type DELETE 
# RoostTestHash=36caaf0283
# 
# 

# ********RoostGPT********
Feature: Delete Purchase Order

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'testToken')
    * configure headers = { Authorization: '#(authToken)' }

  Scenario Outline: Delete purchase order by ID
    Given path 'v2', 'store', 'order', '<orderId>'
    When method delete
    Then status <statusCode>
    And match response == { description: '#(expectedDescription)' }

    Examples:
      | orderId | statusCode | expectedDescription |
      | 1       | 200        | 'Order deleted'     |
      | 0       | 400        | 'Invalid ID supplied' |
      | 999999  | 404        | 'Order not found' |
