# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=cd8cc54cf7
# 
# 

# ********RoostGPT********
Feature: Testing /v2/store/order/{orderId} endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['authToken'] || 'defaultToken'
    * configure headers = { Authorization: '#(authToken)' }

  Scenario: Validating response for valid order ID
    Given path '/v2/store/order', 1
    When method get
    Then status 200
    And match response contains {id:'#number', petId:'#number', quantity:'#number', shipDate:'#?string', status:'#string', complete:'#boolean'}

  Scenario: Validating response for invalid order ID
    Given path '/v2/store/order', 0
    When method get
    Then status 400

  Scenario: Validating response for order ID not found
    Given path '/v2/store/order', 11
    When method get
    Then status 404

  Scenario Outline: Testing various order IDs
    Given path '/v2/store/order', <orderId>
    When method get
    Then status <status>

    Examples:
      | orderId | status |
      | 1       | 200    |
      | 0       | 400    |
      | 11      | 404    |
