# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/logout_get for http method type GET 
# RoostTestHash=696422fb14
# 
# 

# ********RoostGPT********
Feature: User Logout API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'Bearer token')
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Verify successful user logout
  Given path '/v2/user/logout'
  When method post
  Then status 200
  And match response == { "message": "successful operation" }

Scenario: Verify user logout when user is not logged in
  Given path '/v2/user/logout'
  And remove headers['Authorization']
  When method post
  Then status 401
  And match response == { "message": "Unauthorized" }
