# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_delete for http method type DELETE 
# RoostTestHash=5caa5e3efb
# 
# 

# ********RoostGPT********
Feature: User Management API

Background: 
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'default_token')
  * configure headers = {Authorization: '#(authToken)'}

Scenario Outline: Delete user
  Given path '/v2/user/', '<username>'
  When method delete
  Then status <status_code>
  And match response == {description: '<description>'}
  
  Examples: 
    | username | status_code | description            |
    | 'john'   | 400         | 'Invalid username supplied' |
    | 'doe'    | 404         | 'User not found'       |
