# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_get for http method type GET 
# RoostTestHash=b96457affd
# 
# 

# ********RoostGPT********
Feature: Test /v2/user/{username} endpoint

Background: 
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'dummyToken')
  * header Authorization = authToken

Scenario: Test GET method with valid username
  Given path '/v2/user/user1'
  When method get
  Then status 200
  And match response == {id:'#number', username:'user1', firstName:'#string', lastName:'#string', email:'#string', password:'#string', phone:'#string', userStatus:'#number'}

Scenario: Test GET method with invalid username
  Given path '/v2/user/invaliduser'
  When method get
  Then status 400

Scenario: Test GET method with non-existent username
  Given path '/v2/user/nonexistentuser'
  When method get
  Then status 404
