# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_put for http method type PUT 
# RoostTestHash=ec22222bac
# 
# 

# ********RoostGPT********
Feature: User Management

Background:
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'dummyToken')
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario: Updating a user
  Given path '/v2/user/{username}'
  And header Authorization = 'Bearer ' + authToken
  And request { id: '#(id)', username: '#(username)', firstName: '#(firstName)', lastName: '#(lastName)', email: '#(email)', password: '#(password)', phone: '#(phone)', userStatus: '#(userStatus)' }
  When method put
  Then status 200
  And match response == { id: '#integer', username: '#string', firstName: '#string', lastName: '#string', email: '#string', password: '#string', phone: '#string', userStatus: '#integer' }

  Examples:
    | id  | username | firstName | lastName | email           | password | phone       | userStatus |
    | 123 | 'John'   | 'John'    | 'Doe'    | 'john@doe.com'  | 'pass123'| '1234567890'| 1          |
    | 456 | 'Jane'   | 'Jane'    | 'Doe'    | 'jane@doe.com'  | 'pass456'| '0987654321'| 0          |
