# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/login_get for http method type GET 
# RoostTestHash=d905dac95c
# 
# 

# ********RoostGPT********
Feature: User Login API

Background: 
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario: Logs user into the system
  Given path '/v2/user/login'
  And param username = '#(username)'
  And param password = '#(password)'
  When method get
  Then status 200
  And match responseHeaders contains { 'X-Expires-After': '#string', 'X-Rate-Limit': '#number' }
  And match response == '#string'

Scenario: Invalid username/password supplied
  Given path '/v2/user/login'
  And param username = '#(invalidUsername)'
  And param password = '#(invalidPassword)'
  When method get
  Then status 400

Examples:
  | username       | password       | invalidUsername | invalidPassword |
  | 'validUser'    | 'validPass'    | 'invalidUser'   | 'invalidPass'   |
