# ********RoostGPT********

# Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/createWithArray_post for http method type POST 
# RoostTestHash=2fceff8367
# 
# 

# ********RoostGPT********
Feature: User Creation with Array

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.get('authToken', $processEnvironment.AUTH_TOKEN)
    * configure headers = { Authorization: '#(authToken)' }

  Scenario: Verify successful operation of creating users with input array
    Given path '/v2/user/createWithArray'
    And request
    """
    [
      {
        "id": 1,
        "username": "user1",
        "firstName": "User",
        "lastName": "One",
        "email": "user1@example.com",
        "password": "password1",
        "phone": "1234567890",
        "userStatus": 1
      },
      {
        "id": 2,
        "username": "user2",
        "firstName": "User",
        "lastName": "Two",
        "email": "user2@example.com",
        "password": "password2",
        "phone": "0987654321",
        "userStatus": 0
      }
    ]
    """
    When method post
    Then status 200
    And match response == 'successful operation'
    And match $responseHeaders['Content-Type'] == 'application/json'
